### ISSUE TITLE
CollidableBox Collision Struggle & Doorway Transition

### ISSUE THREAD

**Issue by spikeystar** [spikeystar/GGRPG#4]
**CollidableBox struggles with round objects** - want to allow for proper Ysorting of an area with height, but the collisions with the CollidableBox don't fit to larger, round objects well

<img width="642" alt="Screenshot 2024-01-21 at 1 27 26 PM" src="https://github.com/spikeystar/GGRPG/assets/145728899/f32cf2b0-64aa-4f5c-8d27-dc28e6e873b4">

<img width="709" alt="Screenshot 2024-01-21 at 1 27 54 PM" src="https://github.com/spikeystar/GGRPG/assets/145728899/7a87d5f1-3a5d-4fd7-bb7d-557014075fda">

**Doorway Transition** -  created a script called "Doorway" for areas where I want player to have to click "Shift" to enter. Something is not working with my set up as it allows the transition to be enacted from anywhere, not just the corresponding Area2D. See Gary_s House Outside for example.

**Comment by Giwayume** [comment]
The oval platforms are a bit of a weird case. At the moment, you could leave the collision handling to the navmesh. Then for rendering them correctly, split out the sprite for the top of the platform (add DepthTestFloorSprite script to it) from the sprite for the side of the platform (add DepthTestCharacterSprite to that), and mess around with the depth test offsets so it orders correctly.
